import Head from "next/head";
import Header from "./../Componnents/header/index";
import { Divider } from "antd";
import CardSlider from "../Componnents/CardSlider";
import Special from "../Componnents/SpecialCategory";
import { Container } from "react-bootstrap";
import React, { useState } from "react";
import myProduct from "../server/myproducts";
import { connect } from "react-redux";

const Home = () => {
  const products = myProduct.products;

  return (
    <div>
      <Head>
        <title> فروشگاه ولگا گالری|خرید آنلاین پوشاک زنانه</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Header />

        <Divider orientation="center">
          <h2> جدیدترین ها</h2>
        </Divider>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            margin: "2%"
          }}
        >
          {" "}<h5> جدیدترین محصولات فروشگاه ولگا گالری</h5>
        </div>
        <CardSlider products={products} />
        <Divider orientation="center">
          <h2>دسته بندی های ویژه</h2>
        </Divider>
        <Special title="کالکشن بهاره" />
        <Special title=" مانتو" />
        <Special title=" تخفیف دار" />
        <Special title=" ست" />
        <Divider orientation="center">
          <h2> پیشنهادات سوپر ویژه ولگا</h2>
        </Divider>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            margin: "2%"
          }}
        >
          {" "}<h5> جدیدترین محصولات اضافه شده‌ </h5>
        </div>
        <CardSlider products={products} />
      </Container>
    </div>
  );
};
const mapStateToProps = state => {
  return {
    current: state.shop.currentItem
  };
};

export default connect(mapStateToProps)(Home);
